#!/bin/bash

# Before running this, set your default audio interface in the macOS audio preferences
# Make sure it is set to a sampling rate of 44100 or change .csd file accordingly

# Select audio module (coreaudio or portaudio)
AUDIOMODULE=coreaudio


CSD=tuningfork.csd
INSTANCE=Lamento
CSOUND_PORT=9990
OPENSTAGECONTROL_PORT=9991
HOST="127.0.0.1"

launchosc() {
    echo
    for x in $(seq 10); do
        echo $x
        sleep 0.2
    done
            
    /Applications/open-stage-control.app/Contents/MacOS/open-stage-control \
        --osc-port $OPENSTAGECONTROL_PORT \
        --send $HOST:$CSOUND_PORT \
        --load tuningfork-ui.json \
        --theme flat \
        --instance-name "$INSTANCE" \
        --state tuningfork-ui.state \
        --remote-root "$(realpath .)"
                
}

launchosc &

while true; do
    rm --force exitcode.txt
    
    csound -+rtaudio=$AUDIOMODULE --env:CSNOSTOP=yes --omacro:USEOSC=1 "$CSD"

    if [ ! -e exitcode.txt ]; then
        break
    fi 
        
    exitcode="$(cat exitcode.txt)"
    echo "::::: Csound exited, exitcode.txt = $exitcode"
    if [[ "$exitcode" != "0" ]]; then
        echo "::::: Restarting"
        sleep 1
        continue
    fi

    break
done 

echo "::::: Shutting down Open Stage Control"
pkill -f "open-stage-control(.)*$INSTANCE"
sleep 1
echo "::::: Exiting"